version: "3"

services:
  stub-nginx:
    image: nginx:latest
    restart: on-failure
    container_name: stub-nginx
    links:
      - stub-php-fpm:php
    depends_on:
      - stub-php-fpm
    labels:
      traefik.enable: true
      traefik.http.routers.stub-nginx.rule: Host(`${MAIN_HOST}`)
      traefik.http.routers.stub-nginx.entrypoints: http
      traefik.http.services.stub-nginx.loadbalancer.server.port: 80
    volumes:
      - ./../conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./../logs/stub/nginx:/var/log/nginx
      - ./../sites/stub:/var/www:cached

  stub-php-fpm:
    image: registry.gitlab.com/bitrix-k8s/images/php-fpm-8.1:latest
    container_name: stub-php-fpm
    restart: on-failure
    #    ports:
    #      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_SESSION: "docker-server"
    volumes:
      - ./../conf/php-fpm/bitrix.ini:/usr/local/etc/php/conf.d/bitrix.ini:ro
      - ./../conf/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./../sites/stub:/var/www:cached
    depends_on:
      - db
    links:
      - db
    extra_hosts:
      - Host(`example.local`):127.0.0.1
