version: "3"

services:
  stub-nginx:
    image: nginx:latest
    restart: on-failure
    container_name: stub-nginx
    links:
      - stub-php-fpm:php
    depends_on:
      - stub-php-fpm
    labels:
      traefik.enable: true
      traefik.http.routers.stub-nginx.rule: Host(`${MAIN_HOST}`)
      traefik.http.routers.stub-nginx.entrypoints: http
      traefik.http.services.stub-nginx.loadbalancer.server.port: 80
    volumes:
      - ./../conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./../logs/sites/stub/nginx:/var/log/nginx
      - ./../sites/stub:/var/www:cached

  stub-php-fpm:
    image: registry.gitlab.com/bitrix-docker/images/php-fpm-8.1:latest
    container_name: stub-php-fpm
    restart: on-failure
    environment:
      # to enable xdebug
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_SESSION: "docker-server"
      # to skip bitrix server test
      BITRIX_VA_VER: 7.4.3
    volumes:
      - ./../conf/php-fpm/bitrix.ini:/usr/local/etc/php/conf.d/bitrix.ini:ro
      - ./../conf/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./../sites/stub:/var/www:cached
      - ./../logs/sites/stub/php-fpm:/var/log
    depends_on:
      - db
    links:
      - db
    external_links:
      - stub-nginx:Host(`${MAIN_HOST}`)
