version: '3'
services:
  mailhog:
    image: mailhog/mailhog
    container_name: bitrix-mailhog
    restart: always
    environment:
      TZ: "${SERVER_TIMEZONE}"
    logging:
      driver: 'none'
    labels:
      traefik.enable: true
      traefik.http.routers.mailhog.rule: Host(`mailhog.${MAIN_HOST}`) || Host(`www.mailhog.${MAIN_HOST}`)
      traefik.http.routers.mailhog.entrypoints: http,https
      traefik.http.routers.mailhog.tls: ${TRAEFIK_TLS_ENABLED}
      traefik.http.routers.mailhog.tls.certresolver: ${TRAEFIK_CERT_RESOLVER}
      traefik.http.routers.mailhog.middlewares: ${TRAEFIK_MIDDLEWARES}

      traefik.http.services.mailhog.loadbalancer.server.port: 8025
    networks:
      - bitrix