version: '3'
services:
  db:
    image: percona
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./../conf/mysql/bitrix.cnf:/etc/my.cnf.d/bitrix.cnf:ro
      - ./../data/mysql:/var/lib/mysql:cached
    labels:
      traefik.enable: false

  mysql-adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.mysql-adminer.rule: Host(`adminer.${MAIN_HOST}`)
      traefik.http.routers.mysql-adminer.entrypoints: http
      traefik.http.services.mysql-adminer.loadbalancer.server.port: 8080
