version: '3'
services:
  mysql-adminer:
    image: adminer
    container_name: webslon-bitrix-mysql-adminer
    restart: always
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.mysql-adminer.rule: Host(`adminer.${MAIN_HOST}`)
      traefik.http.routers.mysql-adminer.entrypoints: http
      traefik.http.services.mysql-adminer.loadbalancer.server.port: 8080
