version: '3'
services:
  mysql-adminer:
    image: adminer
    container_name: bitrix-mysql-adminer
    restart: always
    environment:
      TZ: "${SERVER_TIMEZONE}"
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.mysql-adminer.rule: Host(`adminer.${MAIN_HOST}`) || Host(`www.adminer.${MAIN_HOST}`)
      traefik.http.routers.mysql-adminer.entrypoints: http,https
      traefik.http.routers.mysql-adminer.tls: ${TRAEFIK_TLS_ENABLED}
      traefik.http.routers.mysql-adminer.tls.certresolver: ${TRAEFIK_CERT_RESOLVER}
      traefik.http.routers.mysql-adminer.middlewares: ${TRAEFIK_MIDDLEWARES}

      traefik.http.services.mysql-adminer.loadbalancer.server.port: 8080
    networks:
      - bitrix
