version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: bitrix-traefik
    restart: unless-stopped
    environment:
      TZ: "${SERVER_TIMEZONE}"
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://0.0.0.0:3100/loki/api/v1/push"
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../data/traefik/letsencrypt:/letsencrypt
      - ./../data/traefik/letsencrypt/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./../config/traefik/traefik.yml:/traefik.yml:ro
      - ./../config/traefik/global/:/global/:ro
    command:
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.${MAIN_HOST}`) || Host(`www.traefik.${MAIN_HOST}`)
      traefik.http.routers.traefik.entrypoints: http,https
      traefik.http.routers.traefik.tls: ${TRAEFIK_TLS_ENABLED}
      traefik.http.routers.traefik.tls.certresolver: ${TRAEFIK_CERT_RESOLVER}
      traefik.http.routers.traefik.middlewares: ${TRAEFIK_MIDDLEWARES}

      traefik.http.middlewares.basic-auth.basicauth.users: '${TRAEFIK_BASIC_AUTH_USERS}'

      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 80
    networks:
      - bitrix
